image: unityci/editor:2021.3.10f1-webgl-1

build:
  script:
    - echo "${UNITY_LICENSE}" | tr -d '\r' | install -D /dev/stdin /root/.local/share/unity3d/Unity/Unity_lic.ulf
    - cat /root/.local/share/unity3d/Unity/Unity_lic.ulf
    - apt-get update && apt-get install ffmpeg -y
    - xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' unity-editor -batchmode -quit -executeMethod BuildCommand.Go -projectPath ./ -logFile /dev/stdout
  artifacts:
    paths:
      - buildy

pages:
  stage: deploy
  script:
    - mv buildy public
  artifacts:
    paths:
      - public
